[project]
name = "first-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "genai>=2.1.0",
    "protobuf>=6.33.0",
    "python-dotenv>=1.2.1",
]
